version: "3.8"
services:
  api: 
    build: . 
    ports:
      - "8080:8181"
    depends_on:
      - db
  db:
    image: 'postgres:12-alpine'
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=poker
      - PGPASSWORD=123456
      - PGPORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4
    container_name: admin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=chhai.chhin52@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - admin-data:/var/lib/pgadmin

volumes:
  db_data:
  admin-data: