version: "3.8"
services:
  pock_api: 
    build: . 
    ports:
      - "8080:8181"
    depends_on:
      - db
  db:
    image: 'postgres:12-alpine'
    container_name: local_pgdb
    restart: always
    ports:
      - "8081:5432"
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=poker
      - PGPASSWORD=123456
      - PGPORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=chhai.chhin52@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: